"""esquema_inicial_v1

Revision ID: 2f108123e640
Revises:
Create Date: 2026-05-04 11:43:25.432120

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f108123e640"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensiones PostgreSQL requeridas (no autogeneradas por Alembic)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "area_conocimiento",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("nivel", sa.SmallInteger(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("sistema_origen", sa.String(length=50), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["area_conocimiento.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "dependencia",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("nombre_corto", sa.String(length=100), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("campus", sa.String(length=100), nullable=True),
        sa.Column("sitio_web", sa.String(length=500), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "paper",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("openalex_id", sa.String(length=50), nullable=True),
        sa.Column("handle_riuat", sa.String(length=100), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "articulo",
                "capitulo",
                "libro",
                "tesis_doctorado",
                "tesis_maestria",
                "tesis_licenciatura",
                "memoria_congreso",
                "reporte_tecnico",
                "preprint",
                "otro",
                name="tipo_paper",
            ),
            nullable=False,
        ),
        sa.Column("titulo", sa.Text(), nullable=False),
        sa.Column("titulo_normalizado", sa.Text(), nullable=True),
        sa.Column("abstract_texto", sa.Text(), nullable=True),
        sa.Column("año", sa.SmallInteger(), nullable=True),
        sa.Column("fecha_publicacion", sa.Date(), nullable=True),
        sa.Column("idioma", sa.String(length=10), nullable=True),
        sa.Column("revista", sa.String(length=500), nullable=True),
        sa.Column("issn", sa.String(length=20), nullable=True),
        sa.Column("editorial", sa.String(length=255), nullable=True),
        sa.Column("volumen", sa.String(length=20), nullable=True),
        sa.Column("numero", sa.String(length=20), nullable=True),
        sa.Column("paginas", sa.String(length=50), nullable=True),
        sa.Column("open_access", sa.Boolean(), nullable=True),
        sa.Column("url_pdf", sa.String(length=1000), nullable=True),
        sa.Column("url_landing", sa.String(length=1000), nullable=True),
        sa.Column("license", sa.String(length=50), nullable=True),
        sa.Column("total_citas", sa.Integer(), nullable=False),
        sa.Column("citas_por_año", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("conceptos", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "embedding_contenido", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.Column(
            "fuente_origen",
            sa.Enum(
                "openalex",
                "vufind_uat",
                "riuat",
                "snii_uat",
                "crossref",
                "orcid",
                "manual",
                name="tipo_fuente",
            ),
            nullable=True,
        ),
        sa.Column("cosecha_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
        sa.UniqueConstraint("openalex_id"),
    )
    op.create_table(
        "simulacion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creada_por", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=500), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("escenario", sa.Text(), nullable=False),
        sa.Column("contexto_adicional", sa.Text(), nullable=True),
        sa.Column("modelo_simulacion", sa.String(length=100), nullable=True),
        sa.Column("temperatura", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("max_tokens_respuesta", sa.Integer(), nullable=True),
        sa.Column("idioma_respuesta", sa.String(length=10), nullable=False),
        sa.Column("formato_esperado", sa.String(length=50), nullable=False),
        sa.Column("filtros_cohorte", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gemelos_seleccionados", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("total_gemelos", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "borrador",
                "en_cola",
                "en_curso",
                "agregando",
                "completada",
                "fallida",
                "cancelada",
                name="estado_simulacion",
            ),
            nullable=False,
        ),
        sa.Column("progreso_porcentaje", sa.SmallInteger(), nullable=False),
        sa.Column("costo_estimado_usd", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("costo_real_usd", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("tokens_consumidos_total", sa.Integer(), nullable=True),
        sa.Column("iniciada_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completada_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("duracion_ms", sa.Integer(), nullable=True),
        sa.Column("sintesis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sintesis_generada_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("resumen_ejecutivo", sa.Text(), nullable=True),
        sa.Column("visibilidad", sa.String(length=20), nullable=False),
        sa.Column("compartida_con", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("error_mensaje", sa.Text(), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tema_tronco_comun",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clave", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("categoria", sa.String(length=100), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave"),
    )
    op.create_table(
        "cuerpo_academico",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=True),
        sa.Column("nombre", sa.String(length=500), nullable=False),
        sa.Column("estatus", sa.String(length=50), nullable=True),
        sa.Column("dependencia_id", sa.UUID(), nullable=True),
        sa.Column("lineas_generacion", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("fecha_registro", sa.Date(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dependencia_id"], ["dependencia.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "persona",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre_completo", sa.String(length=255), nullable=False),
        sa.Column("nombre_normalizado", sa.String(length=255), nullable=False),
        sa.Column("primer_nombre", sa.String(length=100), nullable=True),
        sa.Column("apellido_paterno", sa.String(length=100), nullable=True),
        sa.Column("apellido_materno", sa.String(length=100), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "investigador",
                "docente",
                "estudiante",
                "directivo",
                "administrativo",
                "externo",
                name="tipo_persona",
            ),
            nullable=False,
        ),
        sa.Column("orcid", sa.String(length=19), nullable=True),
        sa.Column("openalex_id", sa.String(length=50), nullable=True),
        sa.Column("scopus_id", sa.String(length=50), nullable=True),
        sa.Column("cvu_conacyt", sa.String(length=20), nullable=True),
        sa.Column("google_scholar_id", sa.String(length=50), nullable=True),
        sa.Column("dependencia_id", sa.UUID(), nullable=True),
        sa.Column("cuerpo_academico_id", sa.UUID(), nullable=True),
        sa.Column("cargo", sa.String(length=255), nullable=True),
        sa.Column(
            "nivel_snii",
            sa.Enum("candidato", "nivel_1", "nivel_2", "nivel_3", "emerito", name="nivel_snii"),
            nullable=True,
        ),
        sa.Column("snii_vigente_hasta", sa.Date(), nullable=True),
        sa.Column("grado_maximo", sa.String(length=100), nullable=True),
        sa.Column("grado_disciplina", sa.String(length=255), nullable=True),
        sa.Column("total_publicaciones", sa.Integer(), nullable=False),
        sa.Column("total_citas", sa.Integer(), nullable=False),
        sa.Column("indice_h", sa.Integer(), nullable=False),
        sa.Column("indice_i10", sa.Integer(), nullable=False),
        sa.Column("primera_publicacion", sa.Date(), nullable=True),
        sa.Column("ultima_publicacion", sa.Date(), nullable=True),
        sa.Column("email_publico", sa.String(length=255), nullable=True),
        sa.Column("sitio_web", sa.String(length=500), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("motivo_baja", sa.Text(), nullable=True),
        sa.Column("fecha_baja", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "fuente_principal",
            sa.Enum(
                "openalex",
                "vufind_uat",
                "riuat",
                "snii_uat",
                "crossref",
                "orcid",
                "manual",
                name="tipo_fuente",
            ),
            nullable=True,
        ),
        sa.Column("embedding_perfil", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cuerpo_academico_id"], ["cuerpo_academico.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["dependencia_id"], ["dependencia.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cvu_conacyt"),
        sa.UniqueConstraint("openalex_id"),
        sa.UniqueConstraint("orcid"),
        sa.UniqueConstraint("scopus_id"),
    )
    op.create_table(
        "coautoria",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("posicion", sa.SmallInteger(), nullable=True),
        sa.Column("total_autores", sa.SmallInteger(), nullable=True),
        sa.Column("es_autor_correspondiente", sa.Boolean(), nullable=False),
        sa.Column("es_primer_autor", sa.Boolean(), nullable=False),
        sa.Column("es_ultimo_autor", sa.Boolean(), nullable=False),
        sa.Column("afiliacion_declarada", sa.Text(), nullable=True),
        sa.Column("confianza_match", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("metodo_match", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["paper.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["persona_id"], ["persona.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("persona_id", "paper_id"),
    )
    op.create_table(
        "documento_corpus",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("titulo", sa.String(length=500), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "pdf_subido",
                "texto_subido",
                "paper_extraido",
                "cv_publico",
                "entrevista",
                "otro",
                name="tipo_documento_corpus",
            ),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum(
                "pendiente",
                "procesando",
                "procesado",
                "error",
                "descartado",
                name="estado_documento",
            ),
            nullable=False,
        ),
        sa.Column("texto_extraido", sa.Text(), nullable=True),
        sa.Column("longitud_caracteres", sa.Integer(), nullable=True),
        sa.Column("longitud_tokens_aprox", sa.Integer(), nullable=True),
        sa.Column("archivo_path", sa.String(length=1000), nullable=True),
        sa.Column("archivo_nombre", sa.String(length=500), nullable=True),
        sa.Column("archivo_mime", sa.String(length=100), nullable=True),
        sa.Column("archivo_tamano_bytes", sa.BigInteger(), nullable=True),
        sa.Column("procesado_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("error_procesamiento", sa.Text(), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["paper.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["persona_id"], ["persona.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gemelo",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("es_version_actual", sa.Boolean(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "sin_corpus",
                "en_proceso",
                "borrador",
                "validado",
                "publicado",
                "archivado",
                "baja_solicitada",
                "error",
                name="estado_gemelo",
            ),
            nullable=False,
        ),
        sa.Column("rasgo_extraversion", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rasgo_neuroticismo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rasgo_responsabilidad", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rasgo_amabilidad", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rasgo_apertura", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "rasgo_honestidad_humildad", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "nivel_extraversion",
            sa.Enum("muy_bajo", "bajo", "medio", "alto", "muy_alto", name="nivel_rasgo"),
            nullable=True,
        ),
        sa.Column(
            "nivel_neuroticismo",
            sa.Enum("muy_bajo", "bajo", "medio", "alto", "muy_alto", name="nivel_rasgo"),
            nullable=True,
        ),
        sa.Column(
            "nivel_responsabilidad",
            sa.Enum("muy_bajo", "bajo", "medio", "alto", "muy_alto", name="nivel_rasgo"),
            nullable=True,
        ),
        sa.Column(
            "nivel_amabilidad",
            sa.Enum("muy_bajo", "bajo", "medio", "alto", "muy_alto", name="nivel_rasgo"),
            nullable=True,
        ),
        sa.Column(
            "nivel_apertura",
            sa.Enum("muy_bajo", "bajo", "medio", "alto", "muy_alto", name="nivel_rasgo"),
            nullable=True,
        ),
        sa.Column(
            "nivel_honestidad_humildad",
            sa.Enum("muy_bajo", "bajo", "medio", "alto", "muy_alto", name="nivel_rasgo"),
            nullable=True,
        ),
        sa.Column("idiolecto", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "posturas_tematicas",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "valores_schwartz",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("score_veracidad", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("score_completitud", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("score_consistencia", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("modelo_perfilador", sa.String(length=100), nullable=True),
        sa.Column("prompt_perfilador_version", sa.String(length=20), nullable=True),
        sa.Column("tokens_consumidos", sa.Integer(), nullable=True),
        sa.Column("costo_generacion_usd", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("duracion_generacion_ms", sa.Integer(), nullable=True),
        sa.Column("validado_por_persona", sa.Boolean(), nullable=False),
        sa.Column("fecha_validacion", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("comentarios_validacion", sa.Text(), nullable=True),
        sa.Column("embedding_gemelo", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("razon_regeneracion", sa.String(length=255), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["persona_id"], ["persona.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("persona_id", "version"),
    )
    op.create_table(
        "persona_area",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=False),
        sa.Column("peso", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("fuente", sa.String(length=50), nullable=True),
        sa.Column("paper_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["area_id"], ["area_conocimiento.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["persona_id"], ["persona.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("persona_id", "area_id"),
    )
    op.create_table(
        "persona_dependencia_historico",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("dependencia_id", sa.UUID(), nullable=True),
        sa.Column("cargo", sa.String(length=255), nullable=True),
        sa.Column("fecha_inicio", sa.Date(), nullable=True),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column("es_actual", sa.Boolean(), nullable=False),
        sa.Column("fuente", sa.String(length=50), nullable=True),
        sa.Column("confianza", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dependencia_id"], ["dependencia.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["persona_id"], ["persona.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario_sistema",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("password_set_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("email_verificado", sa.Boolean(), nullable=False),
        sa.Column(
            "rol",
            sa.Enum(
                "admin",
                "rectoria",
                "asesor",
                "secretaria",
                "investigador",
                "lectura",
                name="rol_usuario",
            ),
            nullable=False,
        ),
        sa.Column("persona_id", sa.UUID(), nullable=True),
        sa.Column("presupuesto_mensual_usd", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("consumido_mes_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("ultimo_login", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["persona_id"], ["persona.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "auditoria",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=True),
        sa.Column("accion", sa.String(length=100), nullable=False),
        sa.Column("entidad_tipo", sa.String(length=50), nullable=True),
        sa.Column("entidad_id", sa.UUID(), nullable=True),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_origen", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario_sistema.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "configuracion_presupuesto",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clave", sa.String(length=100), nullable=False),
        sa.Column("valor_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("actualizado_por", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actualizado_por"], ["usuario_sistema.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave"),
    )
    op.create_table(
        "consumo_llm",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=True),
        sa.Column("operacion", sa.String(length=100), nullable=False),
        sa.Column("modelo", sa.String(length=100), nullable=False),
        sa.Column("tokens_prompt", sa.Integer(), nullable=False),
        sa.Column("tokens_completion", sa.Integer(), nullable=False),
        sa.Column("tokens_total", sa.Integer(), nullable=False),
        sa.Column("costo_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("entidad_tipo", sa.String(length=50), nullable=True),
        sa.Column("entidad_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario_sistema.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cosecha",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "fuente",
            sa.Enum(
                "openalex",
                "vufind_uat",
                "riuat",
                "snii_uat",
                "crossref",
                "orcid",
                "manual",
                name="tipo_fuente",
            ),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum(
                "programada",
                "en_curso",
                "completada",
                "completada_con_errores",
                "fallida",
                "cancelada",
                name="estado_cosecha",
            ),
            nullable=False,
        ),
        sa.Column("programada_para", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("iniciada_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completada_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("duracion_ms", sa.Integer(), nullable=True),
        sa.Column("registros_procesados", sa.Integer(), nullable=False),
        sa.Column("registros_nuevos", sa.Integer(), nullable=False),
        sa.Column("registros_actualizados", sa.Integer(), nullable=False),
        sa.Column("registros_descartados", sa.Integer(), nullable=False),
        sa.Column("errores_count", sa.Integer(), nullable=False),
        sa.Column(
            "configuracion",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("log_resumen", sa.Text(), nullable=True),
        sa.Column("errores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("disparada_por", sa.UUID(), nullable=True),
        sa.Column("disparada_manual", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["disparada_por"], ["usuario_sistema.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "export_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("expira_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ultimo_uso", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("usos_total", sa.Integer(), nullable=False),
        sa.Column("creado_por", sa.UUID(), nullable=True),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["creado_por"], ["usuario_sistema.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "gemelo_corpus_uso",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gemelo_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("documento_id", sa.UUID(), nullable=True),
        sa.Column("longitud_usada", sa.Integer(), nullable=True),
        sa.Column("posicion_orden", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint(
            "(paper_id IS NOT NULL AND documento_id IS NULL) OR (paper_id IS NULL AND documento_id IS NOT NULL)",
            name="ck_gemelo_corpus_uso_exclusivo",
        ),
        sa.ForeignKeyConstraint(["documento_id"], ["documento_corpus.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["gemelo_id"], ["gemelo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["paper_id"], ["paper.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "respuesta_simulacion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("simulacion_id", sa.UUID(), nullable=False),
        sa.Column("gemelo_id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("respuesta_texto", sa.Text(), nullable=False),
        sa.Column(
            "postura",
            sa.Enum(
                "a_favor_fuerte",
                "a_favor",
                "matizado",
                "neutral",
                "en_contra",
                "en_contra_fuerte",
                "no_aplica",
                "sin_clasificar",
                name="postura_respuesta",
            ),
            nullable=False,
        ),
        sa.Column(
            "intensidad",
            sa.Enum("baja", "media", "alta", name="intensidad_respuesta"),
            nullable=True,
        ),
        sa.Column("temas_tocados", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("citas_clave", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("sentimiento", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("tokens_prompt", sa.Integer(), nullable=True),
        sa.Column("tokens_completion", sa.Integer(), nullable=True),
        sa.Column("costo_usd", sa.Numeric(precision=10, scale=5), nullable=True),
        sa.Column("duracion_ms", sa.Integer(), nullable=True),
        sa.Column("modelo_usado", sa.String(length=100), nullable=True),
        sa.Column("error_mensaje", sa.Text(), nullable=True),
        sa.Column(
            "embedding_respuesta", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.Column(
            "metadatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["gemelo_id"], ["gemelo.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["persona_id"], ["persona.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["simulacion_id"], ["simulacion.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("simulacion_id", "gemelo_id"),
    )
    op.create_table(
        "validacion_gemelo",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gemelo_id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("aprobado", sa.Boolean(), nullable=False),
        sa.Column("comentarios", sa.Text(), nullable=True),
        sa.Column("correcciones", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["gemelo_id"], ["gemelo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario_sistema.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # FK diferida: simulacion.creada_por -> usuario_sistema (simulacion se crea antes que usuario_sistema)
    op.create_foreign_key(
        "fk_simulacion_creada_por",
        "simulacion",
        "usuario_sistema",
        ["creada_por"],
        ["id"],
        ondelete="RESTRICT",
    )
    # FK diferida: paper.cosecha_id -> cosecha (paper se crea antes que cosecha)
    op.create_foreign_key(
        "fk_paper_cosecha",
        "paper",
        "cosecha",
        ["cosecha_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Eliminar FKs diferidas primero
    op.drop_constraint("fk_simulacion_creada_por", "simulacion", type_="foreignkey")
    op.drop_constraint("fk_paper_cosecha", "paper", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validacion_gemelo")
    op.drop_table("respuesta_simulacion")
    op.drop_table("gemelo_corpus_uso")
    op.drop_table("export_token")
    op.drop_table("cosecha")
    op.drop_table("consumo_llm")
    op.drop_table("configuracion_presupuesto")
    op.drop_table("auditoria")
    op.drop_table("usuario_sistema")
    op.drop_table("persona_dependencia_historico")
    op.drop_table("persona_area")
    op.drop_table("gemelo")
    op.drop_table("documento_corpus")
    op.drop_table("coautoria")
    op.drop_table("persona")
    op.drop_table("cuerpo_academico")
    op.drop_table("tema_tronco_comun")
    op.drop_table("simulacion")
    op.drop_table("paper")
    op.drop_table("dependencia")
    op.drop_table("area_conocimiento")
    # ### end Alembic commands ###
    # Nota: no eliminamos las extensiones porque pueden ser usadas por otras bases de datos
